version: '3.9'
services:
  mf-dev:
    build: .
    container_name: mf-monorepo-dev
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/host-app/node_modules
      - /app/arcane-mf/node_modules
      - /app/tlou-mf/node_modules
      - /app/shared-entities/node_modules
    ports:
      - "3000:3000"   # host-app (Vite en 3000)
      - "3001:3001"   # arcane-mf
      - "3002:3002"   # tlou-mf
    command: sh -c "pnpm --filter host-app run dev & pnpm --filter arcane-mf run watch & pnpm --filter tlou-mf run watch && tail -f /dev/null"
    environment:
      - NODE_ENV=development
